export const FunEvents = [
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Coming Soon`,
    description: `Coming soon`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Coming Soon`,
    description: `Coming soon`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Coming Soon`,
    description: `Coming soon`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Coming Soon`,
    description: `Coming soon`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Coming Soon`,
    description: `Coming soon`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Coming Soon`,
    description: `Coming soon`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Coming Soon`,
    description: `Coming soon`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Coming Soon`,
    description: `Coming soon`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Coming Soon`,
    description: `Coming soon`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Coming Soon`,
    description: `Coming soon`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
];
