export const ProShows = [
  {
    club: `HeartBeats`,
    rulebook: `https://drive.google.com/open?id=1MW7JKs6P3QLbeyG16vx1MrIc0aEUvlWA`,
    name: `Maktub`,
    description: `Join us for a magical evening of music under the stars.`,
    posterurl: `https://res.cloudinary.com/drf3eatfm/image/upload/v1768921355/nitrutsav-2026/z1od7xwbjjn0vincg82e.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Prom Night`,
    description: `Join us for a magical evening of dance and music under the stars.`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Star Night`,
    description: `Experience the galaxy like never before with our immersive astronomy show.`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `DJ Night`,
    description: `Dance to electrifying beats by top DJs from across the country.`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Comedy Night`,
    description: `Laugh out loud with hilarious performances by renowned stand-up comedians.`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Rock Band Night`,
    description: `Feel the adrenaline as live rock bands set the stage on fire.`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Indie Vibes`,
    description: `A soulful evening featuring indie artists and original compositions.`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Classical Fusion`,
    description: `A unique blend of classical melodies with modern musical elements.`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Open Mic Night`,
    description: `Witness raw talent as performers take the stage for an open mic session.`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `EDM Carnival`,
    description: `High-energy EDM performances with stunning lights and visuals.`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Retro Night`,
    description: `Travel back in time with classic hits and retro-themed performances.`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
];
