export const ProShows = [
  {
    club: `HeartBeats`,
    rulebook: `https://drive.google.com/open?id=1MW7JKs6P3QLbeyG16vx1MrIc0aEUvlWA`,
    name: `Maktub`,
    description: `Join us for a magical evening of music under the stars.`,
    posterurl: `https://res.cloudinary.com/drf3eatfm/image/upload/v1768925861/nitrutsav-2026/r0qr1syzchukdowocq4l.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Coming Soon`,
    description: `Coming soon`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Coming Soon`,
    description: `Coming soon`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Coming Soon`,
    description: `Coming soon`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Coming Soon`,
    description: `Coming soon`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Coming Soon`,
    description: `Coming soon`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Coming Soon`,
    description: `Coming soon`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Coming Soon`,
    description: `Coming soon`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Coming Soon`,
    description: `Coming soon`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Coming Soon`,
    description: `Coming soon`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Coming Soon`,
    description: `Coming soon`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
];
